[package]
name = "prometheum"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

repak = { git = "https://github.com/trumank/repak.git" }
sha2 = "0.11"
hex = "0.4"
zip = { version = "8.6", default-features = false, features = ["deflate"] }
lru = "0.18"
tracing-subscriber = "0.3.23"

[dev-dependencies]
tempfile = "3.27"